'''
Created on 6 de abr de 2018

@author: Edison Klafke Fillus


Generator do lazy evaluation. So you can use it for large data without get out of memory/processing

'''
# Create generator object: result
result = (num for num in range(31))

# Print the first 5 values
print(next(result))
print(next(result))
print(next(result))
print(next(result))
print(next(result))

# Print the rest of the values
for value in result:
    print(value)
    
    

# Create a list of strings: lannister
lannister = ['cersei', 'jaime', 'tywin', 'tyrion', 'joffrey']

# Create a generator object: lengths
lengths = (len(person) for person in lannister)

# Iterate over and print the values in lengths
for value in lengths:
    print(value)
    
    
    
# Define generator function get_lengths
def get_lengths(input_list):
    """Generator function that yields the
    length of the strings in input_list."""

    # Yield the length of a string
    for person in input_list:
        yield len(person)  #Lazy evaluation

# Print the values generated by get_lengths()
for value in get_lengths(lannister):
    print(value)
